version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=${MONGODB_URI}
        - MONGODB_DB=${MONGODB_DB}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - REDIS_URL=${REDIS_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
    container_name: thansohoc-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    networks:
      - thansohocnet

  backend:
    build:
      context: ./backend
    container_name: thansohoc-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=${REDIS_URL}
    networks:
      - thansohocnet

  redis:
    image: redis:alpine
    container_name: thansohoc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - thansohocnet

volumes:
  redis-data:

networks:
  thansohocnet:
    driver: bridge 